### ISSUE TITLE
new release tag, for OCEAN, by 2023-05-19

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/formatters#140]
Blocked by 

 - [x] https://github.com/insightsengineering/formatters/pull/144

# TODOs

- [x] #149
- [x]  Tag the update as a release candidate, v0.5.0-rc1
- [x]  Submit v0.5.0-rc1 for validation
- [x]  Get v0.5.0-rc1 validated, retag as v0.5.0
- [x] #156
- [x] #157
